### ISSUE TITLE
`ToyModule` unnecessarily reimplements `.toy_new`

### ISSUE THREAD

**Issue by tomstuart** [adrianna-chang-shopify/ruby-object-model#10]
As a result of #9, the `.toy_new` class method is unnecessarily reimplemented in `ToyModule` when we would expect to be able simply to inherit `ToyObject`’s implementation.

**Comment by adrianna-chang-shopify** [comment]
Closed by https://github.com/adrianna-chang-shopify/ruby-object-model/pull/7
