### ISSUE TITLE
The `#call_method` test helper is not reusable for different receivers

### ISSUE THREAD

**Issue by tomstuart** [adrianna-chang-shopify/ruby-object-model#11]
In each test, the `#call_method` helper is not reusable because it refers to a hardcoded instance variable rather than taking an explicit receiver as an argument.

If we could pass in the receiver, we’d be able to use the helper for sending messages to objects other than the primary subject of each test.

(In fact, perhaps we could then define it once and share that implementation across all the tests.)

**Comment by tomstuart** [comment]
I think you fixed this in #17.

**Comment by adrianna-chang-shopify** [comment]
Closed by #17
