### ISSUE TITLE
The `#call_method` test helper does not use our public API

### ISSUE THREAD

**Issue by tomstuart** [adrianna-chang-shopify/ruby-object-model#12]
The `#call_method` implementations variously make use of `#is_a?` and `#class`, even though they should really be using the “public API” of `#toy_is_a?` (not even implemented) and `#toy_class` when dealing with toyland objects.

This is a chicken-and-egg situation because the reason we’re asking these things in the first place is so we can decide whether to prepend the `toy_` prefix to the message selector.

If we instead provided an explicit prefix as part of our test metaprogramming loop, and passed that prefix into `#call_method`, we could avoid having to make this decision at all.

**Comment by tomstuart** [comment]
I think you fixed this in #17.

**Comment by adrianna-chang-shopify** [comment]
Closed via #17
