### ISSUE TITLE
`assert_kind_of` doesn’t use our public API

### ISSUE THREAD

**Issue by tomstuart** [adrianna-chang-shopify/ruby-object-model#14]
We’re using `#kind_of?` (via `assert_kind_of`) in one of the `ToyClass` tests, which again is not part of our public API. We should either rewrite the test to use methods we have implemented, or implement `#toy_kind_of?` so that we can legitimately call it.

**Comment by tomstuart** [comment]
I think #20 fixes this, because we replaced…

```ruby
assert_kind_of object_klass, call_method(@class, meth_prefix, :new)
```

…with…

```ruby
assert_equal @class, call_method(call_method(@class, meth_prefix, :new), meth_prefix, :class)
```

…, i.e. we’re now checking the object’s immediate class rather than taking its ancestry into account.

**Comment by adrianna-chang-shopify** [comment]
Indeed, #20 fixes this!
