### ISSUE TITLE
Our classes don’t live in a `Toy` namespace

### ISSUE THREAD

**Issue by tomstuart** [adrianna-chang-shopify/ruby-object-model#16]
Our toyland classes are called `ToyObject`, `ToyModule` and `ToyClass`, which suggests they should really live in a `Toy` namespace and be called `Toy::Object`, `Toy::Module` and `Toy::Class` instead.

**Comment by tomstuart** [comment]
#19 briefly put our (rebooted) classes into a `NewImpl` namespace, but #20 moved them out again.

**Comment by adrianna-chang-shopify** [comment]
Closed by https://github.com/adrianna-chang-shopify/ruby-object-model/pull/22!
