### ISSUE TITLE
Fill in remaining gaps in Toy Object API

### ISSUE THREAD

**Issue by adrianna-chang-shopify** [adrianna-chang-shopify/ruby-object-model#26]
From @tomstuart's comment [here](https://github.com/adrianna-chang-shopify/ruby-object-model/pull/25#pullrequestreview-847688008):

> Perhaps more significantly, we’re now in a better position to be able to fill any accidental gaps which exist in our implementation (and aren’t checked by the tests); for example, none of these currently work:

> * Toy::Object.instance_variables, Toy::Module.instance_variables, Toy::Class.instance_variables (et al)
> * Toy::Object.constants, Toy::Module.constants, Toy::Class.constants (et al)
> * Toy::Object.instance_methods, Toy::Module.instance_methods, Toy::Class.instance_methods (et al)
> * Toy::Object.new.to_s, Toy::Module.new.to_s, Toy::Class.new.to_s
> * Toy::Object.new.inspect
> * Toy::Object.new.kind_of?, Toy::Module.new.kind_of?, Toy::Class.new.kind_of?

> Now that we have mixins which provide (some of) these, can we plug all the holes?

**Comment by tomstuart** [comment]
Perhaps it would’ve been clearer to say:

* the `Toy::Object`, `Toy::Module` and `Toy::Class` classes are missing the fundamental behaviour of objects (bag of instance variables) and modules (bag of constants and method definitions)
* `Toy::Object`, `Toy::Module` and `Toy::Class` instances are missing some superficial behaviour of objects (`#to_s`, `#inspect`, `#kind_of`)
