### ISSUE TITLE
Our toy object model is not yet fully rigorous

### ISSUE THREAD

**Issue by tomstuart** [adrianna-chang-shopify/ruby-object-model#8]
Good news everyone! While I was reading through the code in #7 I came up with a miscellaneous list of ~pedantic nitpicks~ rigour improvement opportunities™ that I thought we might choose to pause and address before we continue onward. These are all essentially optional but I wanted to share them in one place to make them easier to discuss.

* [x] #9 
* [x] #10
* [x] #11
* [x] #12
* [x] #13
* [x] #14
* [x] #15
* [x] #16
* [x] #18

**Comment by adrianna-chang-shopify** [comment]
We did it! ✨
